/*
 * Auto-generated by packages/db/scripts/consolidate-product-families.mjs
 * Mapping de slugs legacy (productos archivados al consolidar familias)
 * hacia el producto base + variant pre-seleccionado.
 *
 * Usado por proxy.ts (Next.js middleware) para redirect 301.
 * NO editar a mano. Re-generar con: make consolidate-product-families
 */

export const PRODUCT_REDIRECTS: Record<string, string> = {
  "set-6-fotoimanes-polaroid-grande":
    "set-12-fotoimanes-polaroid?variant=cmp61wrtc0001jypzl2zkggex",
  "set-9-fotoimanes-polaroid-color": "set-12-fotoimanes-polaroid?variant=cmp61wsah0003jypz0ssyrktu",
  "set-20-mini-polaroids": "set-12-fotoimanes-polaroid?variant=cmp61wt210007jypz5j9ipwpe",
  "mini-box-dia-mama": "big-box-dia-mama?variant=cmp61wxen000bjypz2ixpaayd",
  "rutina-infantil-xl-9": "rutina-infantil-7-actividades?variant=cmp61x02g000fjypz44exbepn",
};
