-- supabase/migrations/00000000000004_sync_auth_users_delete.sql
--
-- DEPRECATED — trigger SQL directo descartado.
--
-- Intento original (commit e3ccc5a, 2026-05-11):
--   Trigger AFTER DELETE en auth.users → función que borra Customer y
--   AdminUser correspondientes vía supabaseUserId.
--
-- Por qué se descarta:
--   La Supabase Auth API (HTTP) rompe el flujo completo de admin.deleteUser
--   con error 500 "Database error deleting user" cuando hay cualquier
--   trigger custom en auth.users que referencia tablas en schema public,
--   AUNQUE la función tenga:
--     - SECURITY DEFINER con owner postgres
--     - GRANT EXECUTE a supabase_auth_admin, postgres, service_role
--     - GRANT SELECT, DELETE en las tablas a supabase_auth_admin
--     - Cast OLD.id::text correcto
--     - EXCEPTION handler defensivo
--
--   El trigger ni siquiera se dispara (verificado con tabla de debug).
--   Para arreglarlo de raíz haría falta ALTER FUNCTION ... OWNER TO
--   supabase_auth_admin, pero requiere SET ROLE supabase_auth_admin que
--   no tiene el rol postgres del DATABASE_URL.
--
--   SQL DELETE directo en auth.users SÍ dispara el trigger correctamente
--   (verificado: cascade Customer 1→0). Solo la API HTTP rompe.
--
-- Decisión:
--   Limpieza de huérfanos se hace fuera de banda:
--   - Dev/testing: `FORCE=1 make seed-clean` borra TODO (auth.users +
--     Customer + AdminUser explícitamente).
--   - Producción futura (Fase 4 Right-to-Deletion Ley 1581): vamos a
--     implementar Supabase Database Webhooks o un pg_cron periódico que
--     sí tienen workarounds documentados.
--
-- Defensivo (idempotente): si una versión previa de la migración dejó
-- el trigger/función creados, los limpiamos. Re-ejecutar el script no
-- causa error.

DROP TRIGGER IF EXISTS on_auth_user_deleted ON auth.users;
DROP FUNCTION IF EXISTS public.handle_auth_user_delete();
